common: &common
  adapter: postgresql
  username: rails 
  password: rails # from psql setup, see Postgresql

development:
  <<: *common
  database: sample_development

test:
  <<: *common
  database: sample_test

production:
  <<: *common
  database: sample_production

